version: '3.3'
services:
  metabase:
    build: ./metabase
    container_name: metabase
    hostname: metabase
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: /run/secrets/db_user
      MB_DB_PASS: /run/secrets/db_password
      MB_DB_HOST: postgres
    networks: 
      - metanet1
    depends_on: 
      - postgres
    secrets:
      - db_password
      - db_user

  postgres:
    image: postgres:13.3
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: /run/secrets/db_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - metanet1
    secrets:
      - db_password
      - db_user
networks: 
  metanet1:
    driver: bridge
secrets:
   db_password:
     file: db_password.txt
   db_user:
     file: db_user.txt